### ISSUE TITLE
Create Objects

### ISSUE THREAD

**Issue by BrandonKlotz** [BrandonKlotz/pos-lab#1]

**Comment by HollyJHuber** [comment]
"A list of twelve products that have properties for: name, category, description, and price."

12 items (which are objects) named item01, item02 ... item12

each falls under one of the following three categories:

SMOKEABLES
Alaskan Thunder
Purple Haze
Pineapple Express
Maui Wowie
Kingdom of Kush
After School Special

EDIBLES
gummies
brownies
elixir

ACCESSORIES
bowl 
grinder
pipe

For now, we will work with generic descriptions and simple price of $1 each so the math is super easy to check. These will be very easy and fun to change. Hoping we can come up with some fun descriptions!!!

**Comment by HollyJHuber** [comment]
we wont' be using named items (item01 ...) but instead an array of items with a unique ID for easily matching a particular item. Shopping cart list will also be an array! This will be fun becuase unlike JavaScript, jQuery is auto-iterating so no for loops or forEach should be necessary!
